### ISSUE TITLE
Systemabsturz nach Installation des Bündels

### ISSUE THREAD

**Issue by deralteherr** [heimrichhannot/contao-teaser-bundle#1]
Guten Tag,
bei dem Versuch, das Bündel "contao-teaser-bundle" auf einem System 4.5.12 zu installieren, ist mein System komplett abgeschossen worden.

Frontend: weißer Schirm,
Backend: weißer Schirm,
Manager: Fehler 500 mit dieser Meldung:

ERROR 500 The Contao version could not be determined
The console returned unexpected content when asked for the Contao version. Please check the output for more information:   In DefinitionErrorExceptionPass.php line 37:  Cannot autowire service "huh.teaser.listener.dc.content": argument "$framew  ork" of method "HeimrichHannot\ContaoTeaserBundle\DataContainer\ContentList  ener::__construct()" references interface "Contao\CoreBundle\Framework\Cont  aoFrameworkInterface" but no such service exists. You should maybe alias th  is interface to the existing "contao.framework" service.

Kann ich das System irgendwie wieder (händisch?) reparieren?

Viele Grüße,
Rudolf
![bildschirmfoto 2018-08-17 um 19 44 56](https://user-images.githubusercontent.com/19323337/44296449-b8f02800-a2bf-11e8-9194-31514208fb66.png)

**Comment by koertho** [comment]
Hallo, kannst du es bitte nochmal mit der neuen Version 0.1.2 testen? Wir hatten leider debug Code in der Service definition vergessen. Sollte es dann immer noch nicht funktionieren, liegt der Fehler bei Contao, allerdings könnten wir diesen auch in unserem Bundle "umgehen".

**Comment by koertho** [comment]
Ich habe nochmal im Core geschaut und das Problem auf unserer Seite behoben. Mit Version 0.1.3 sollte es nun funktionieren.

**Comment by deralteherr** [comment]
Guten Abend,
ich werde testen, allerdings komme ich heute nicht mehr dazu.
Viele Grüße
Rudolf

**Comment by deralteherr** [comment]
Guten Morgen,
die Installation hat jetzt geklappt.
Ganz mit ohne Fehler 500 und Komplettabsturz.
Grüße,
Rudolf

**Comment by koertho** [comment]
Das freut mich :)

**Comment by deralteherr** [comment]
Hallo Thomas,
mit Contao 4.6.2 klappt es nicht mehr:

—————————————————————————————————

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install symfony/symfony v3.4.7
    - Conclusion: don't install symfony/asset v4.1.4|install symfony/symfony v3.4.7
    - Installation request for heimrichhannot/contao-teaser-bundle ^0.1.3 -> satisfiable by heimrichhannot/contao-teaser-bundle[0.1.3].
    - don't install symfony/symfony v3.4.0|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.1|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.10|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.11|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.12|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.13|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.14|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.15|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.2|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.3|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.4|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.5|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.6|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.8|don't install symfony/asset v4.1.4
    - don't install symfony/symfony v3.4.9|don't install symfony/asset v4.1.4
    - Installation request for symfony/asset (locked at v4.1.4) -> satisfiable by symfony/asset[v4.1.4].
    - Conclusion: don't install symfony/framework-bundle v4.1.4|install symfony/symfony v3.4.0|install symfony/symfony v3.4.1|install symfony/symfony v3.4.10|install symfony/symfony v3.4.11|install symfony/symfony v3.4.12|install symfony/symfony v3.4.13|install symfony/symfony v3.4.14|install symfony/symfony v3.4.15|install symfony/symfony v3.4.2|install symfony/symfony v3.4.3|install symfony/symfony v3.4.4|install symfony/symfony v3.4.5|install symfony/symfony v3.4.6|install symfony/symfony v3.4.7|install symfony/symfony v3.4.8|install symfony/symfony v3.4.9
    - heimrichhannot/contao-teaser-bundle 0.1.3 requires heimrichhannot/contao-utils-bundle ^2.28 -> satisfiable by heimrichhannot/contao-utils-bundle[2.28.0, 2.28.1, 2.28.2, 2.28.3, 2.28.4, 2.28.5, 2.28.6, 2.28.7, 2.28.8, 2.28.9].
    - heimrichhannot/contao-utils-bundle 2.28.9 requires symfony/framework-bundle ^3.4 -> satisfiable by symfony/symfony[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9], symfony/framework-bundle[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - heimrichhannot/contao-utils-bundle 2.28.8 requires symfony/framework-bundle ^3.4 -> satisfiable by symfony/symfony[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9], symfony/framework-bundle[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - heimrichhannot/contao-utils-bundle 2.28.7 requires symfony/framework-bundle ^3.4 -> satisfiable by symfony/symfony[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9], symfony/framework-bundle[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - heimrichhannot/contao-utils-bundle 2.28.6 requires symfony/framework-bundle ^3.4 -> satisfiable by symfony/symfony[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9], symfony/framework-bundle[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - heimrichhannot/contao-utils-bundle 2.28.5 requires symfony/framework-bundle ^3.4 -> satisfiable by symfony/symfony[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9], symfony/framework-bundle[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - heimrichhannot/contao-utils-bundle 2.28.4 requires symfony/framework-bundle ^3.4 -> satisfiable by symfony/symfony[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9], symfony/framework-bundle[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - heimrichhannot/contao-utils-bundle 2.28.3 requires symfony/framework-bundle ^3.4 -> satisfiable by symfony/symfony[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9], symfony/framework-bundle[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - heimrichhannot/contao-utils-bundle 2.28.2 requires symfony/framework-bundle ^3.4 -> satisfiable by symfony/symfony[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9], symfony/framework-bundle[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - heimrichhannot/contao-utils-bundle 2.28.1 requires symfony/framework-bundle ^3.4 -> satisfiable by symfony/symfony[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9], symfony/framework-bundle[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - heimrichhannot/contao-utils-bundle 2.28.0 requires symfony/framework-bundle ^3.4 -> satisfiable by symfony/symfony[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9], symfony/framework-bundle[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Can only install one of: symfony/framework-bundle[v3.4.0, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.1, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.10, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.11, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.12, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.13, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.14, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.15, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.2, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.3, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.4, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.5, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.6, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.7, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.8, v4.1.4].
    - Can only install one of: symfony/framework-bundle[v3.4.9, v4.1.4].
    - Installation request for symfony/framework-bundle (locked at v4.1.4) -> satisfiable by symfony/framework-bundle[v4.1.4].

<warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
Finished Composer Cloud resolving.

————————————————————————————————

Viele Grüße,
Rudi

**Comment by koertho** [comment]
@deralteherr Da es sich hier um einen anderen Fehler handelt, verschiebe ich das ganze mal in ein neues Issue.
