### ISSUE TITLE
No fields for editing/configure link teaser element type after updating Contao from 4.11.x to 4.12.x

### ISSUE THREAD

**Issue by Baloobear** [heimrichhannot/contao-teaser-bundle#13]
**Context**
Contao version: 4.12.1
Bundle version: 1.4.0
PHP version: 7.4

**Description**
After updating my Contao from 4.11.x to 4.12.1 (because of the ending support period of 4.11.x) I cannot edit any content of the "Link-Teaser" content type because there are no more fields available. The page still shows all the content but I'm unable to change anything on this content type.

Creating a new content type "Link-Teaser" shows up all available fields. Must I re-create all my link teaser elements again or is there a kind of migration available?

Any help is appreciated.

Kind regards,
Dennis

**Comment by koertho** [comment]
That's strange, but we've not tested this bundle with contao 4.12 yet, as we only use LTS-Versions. I can't promise a fix soon, but if you can find the error leading to this problem, you're welcome to report it or do a pull request.

**Comment by Baloobear** [comment]
Is there a chance to debug this behaviour in any way? I don't have any kind of error messages in the log files.

I would like to support you as good as I can but I don't have a clue what information you need or where I need to look at.

I also found out that creating new content elements of the type "Link-Teaser" don't let me change the "wording" of the "more" link text. It's always getting back to "custom". (Maybe this may be the source of the problem of not showing editing fields on old entries, too.)

**Comment by koertho** [comment]
I really can't explain this behavior, I also had it with some options (but not all) and it was also reported here #12 
I would start debugging this by going through the complete dc save mechanic.

**Comment by koertho** [comment]
@Baloobear This problem should be fixed with 1.4.1

**Comment by Baloobear** [comment]
Thanks,

with the update the plugin works again.
