### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by funkytown-productions** [heimrichhannot/contao-teaser-bundle#15]
**Context**
Contao version: 4.12.5
Bundle version: 
PHP version: 7.4

**Description**
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
97 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> @php vendor/bin/contao-setup
Parse error: syntax error, unexpected 'isset' (T_ISSET), expecting identifier (T_STRING) in /home/qg478nap/www/home/vbs/vendor/heimrichhannot/contao-teaser-bundle/src/DataContainer/ContentContainer.php on line 177
Script @php vendor/bin/contao-setup handling the post-install-cmd event returned with error code 255
# Process terminated with exit code 255
# Result: Unknown error

**Comment by koertho** [comment]
Fixed in 2.0.1, thanks for reporting!
