### ISSUE TITLE
Migration does not work

### ISSUE THREAD

**Issue by Burte** [heimrichhannot/contao-teaser-bundle#16]
**Context**
Contao version: 4.13.8
Bundle version:
PHP version: 7.4

**Description**
Datenbankmigrationen does not work.

**Comment by koertho** [comment]
A little more information like the error message would be helpful.

**Comment by Burte** [comment]
Datenbank-Migrationen
 Eine ausstehende Datenbank-Migration
Datenbankmigrationen stellen konsistente Daten und Tabellenschemas sicher.
-> klick on "Datenbank überprüfen"
-> Datenbank-Änderungen
Die Datenbank ist nicht aktuell. Bitte prüfe die untenstehende Konsolenausgabe und führe die Änderungen aus.
-> klick on "Datenbank-Änderungen" ausführen
-> Änderungen erfolgreich
-> Ergebnis: Die Datenbank ist nicht aktuell. Bitte prüfe die untenstehende Konsolenausgabe und führe die Änderungen aus.

**Comment by koertho** [comment]
Die "untenstehende Konsolenausgabe" wäre das spannende gewesen ;)

**Comment by Burte** [comment]
ce_page_teaser to Teaser Bundle Migration

ce_page_teaser Migration successfull! Migrated 0 page_teaser and 0 teaser elements.

**Comment by koertho** [comment]
Hi, yes, the plan was that salteax do a PR while I'm on vacation. Didn't worked out :)
I will fix it today.

**Comment by koertho** [comment]
Can you please test if #17 fix your issues?

**Comment by Burte** [comment]
Test is negative. No database migration furthermore.

**Comment by koertho** [comment]
@Burte Thanks for testing. I will merge it soon.

**Comment by pixelmatty** [comment]
Hi koertho

Don't know if I did right: I copied #17 (except red marked sectors) and replaced CePageteaserMigration.php in vendor ... (no prod cache clear in between)
Now starting Contao Manager there is no more pending database migration info.
All seems to work(?)

**Comment by koertho** [comment]
It is better to install it through composer, but, yes, basically it was correct ;)

**Comment by koertho** [comment]
Fixed in 2.0.8

**Comment by pixelmatty** [comment]
Yes shure, I only tested it before you launched 2.0.8 ;-)
Thanks very much.

**Comment by koertho** [comment]
@pixelmatty You can also install branches through Composer ;)
