### ISSUE TITLE
2.0.12 Problem

### ISSUE THREAD

**Issue by pixelmatty** [heimrichhannot/contao-teaser-bundle#18]
**Context**
Contao version: 4.13.x
Bundle version: 2.0.12
PHP version: 8x

**Description**
Updating the teaser bundle tu the latest version 2.0.12 causes a database error in contao. Login to the contao database isn't possible anymore.

**Comment by fiedsch** [comment]
See https://community.contao.org/de/showthread.php?85883-Bei-Ionos-Installation-keine-Datenbankverbindung-möglich&p=577317&viewfull=1#post577317

I tried to reproduce the issue, but failed to generate any errors.

**Comment by pixelmatty** [comment]
Thanks. I think it was a Problem with Contao composer update (although other plugins didn'n cause this problem when updating). But now the update worked.

**Comment by pixelmatty** [comment]
Thanks. I think it was a Problem with Contao composer update (although other plugins didn'n cause this problem when updating). But now the update worked.

**Comment by pixelmatty** [comment]
Thanks. I think it was a Problem with Contao composer update (although other plugins didn'n cause this problem when updating). But now the update worked.
