### ISSUE TITLE
Externe URL als Weiterleitungsziel nicht auswählbar

### ISSUE THREAD

**Issue by bizon1** [heimrichhannot/contao-teaser-bundle#3]
Wenn man externe URL als Weiterleitungsziel auswählt, erscheint folgende Fehlermeldung.

`Type error: Too few arguments to function HeimrichHannot\ContaoTeaserBundle\DataContainer\ContentListener::__construct(), 0 passed in /datadisk/www/mlp/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php on line 171 and exactly 1 expected`

Der Datensatz ist dadurch nicht mehr weiter bearbeitbar, so dass auch keine Korrekturen mehr möglich sind. Man muss direkt in der Datenbank reparieren, um weiterarbeiten zu können.
Den Fehler habe ich in Contao-4.4.24 und 4.6.3 festgestellt.

**Comment by stefan-at-work** [comment]
Kann ich bestätigen.
