### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Kahmoon** [heimrichhannot/contao-teaser-bundle#8]
Hi,

i opened a seperate issue/enhancement

> in description of this module it says "custom text for more links". I cannot set this text manually in the element it self. Sometimes the label "more information" is not the best option. So isn´t "Seite x besuchen". Did i miss any configuration?

The solution via variable ($GLOBALS['TL_LANG']['MSC']['linkteaser']['teaserlinktext') is kinda static too.  A custom field or another option in the link type dropdown for "link text" (like in element hyperlink) would be great and super flexible!

VG Frank

**Comment by koertho** [comment]
Hi, the problem with an normal text field is, that it would not be multilingual. But if you really need that feature, you are welcome to do a pull request. I don't know when we will find time to add such a feature.

**Comment by koertho** [comment]
@Kahmoon If you still need this feature, it's implemented now ;)

**Comment by Kahmoon** [comment]
Thanks. I can choose this new option but i cannot see a field to enter text?

<img width="2746" alt="Bildschirmfoto 2021-09-07 um 09 31 21" src="https://user-images.githubusercontent.com/6390770/132303270-2489c382-f887-431d-b6da-8fb7645ea275.png">
